name: taskmaster_app
description: A cross-platform party game app for Taskmaster-style challenges

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Firebase - Temporarily use updated versions to fix compilation
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.1
  
  # UI Components
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  shimmer: ^3.0.0
  
  # Utilities
  uuid: ^3.0.7
  intl: ^0.18.1
  collection: ^1.17.2
  get_it: ^7.6.0
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.1
  
  # Location Services
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  
  # Monetization (commented out for initial testing)
  # google_mobile_ads: ^4.0.0
  # in_app_purchase: ^3.1.11
  
  # AR Support (commented out - requires additional setup)
  # ar_flutter_plugin: ^0.7.3
  
  # AI Integration
  http: ^1.1.0
  
  # Additional Utils
  share_plus: ^7.2.1
  url_launcher: ^6.2.1
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.4
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/data/